name: Update Recommendations JSON

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows manual triggering of workflow

permissions:
    contents: write

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3

      - name: Clone Another Repository
        run: |
          git clone https://github.com/Azure/Azure-Proactive-Resiliency-Library-v2.git cloned-repo

      - name: Run PowerShell Script to Generate JSON
        shell: pwsh
        run: |
          .github/scripts/Build-Recommendation-Object.ps1

          - name: Commit and Push JSON
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            # Check if the file has changes
            if [ -n "$(git status --porcelain docs/objects/recommendations.json)" ]; then
              git add docs/objects/recommendations.json
              git commit -m "Update recommendations.json"
              git push
            else
              echo "No changes to commit"
            fi
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}